### ISSUE TITLE
Site privacy settings shouldn’t appear when group is linked to external site

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/openlab-theme#179]
See, for example, Test Student’s portfolio, which is linked to an external site.  When I go to portfolio settings, the site privacy settings still appear, even though they can't be changed.  Can we hide them when the group is linked to an external site?

Thanks!

<img width="1188" alt="externalsiteprivacysettings" src="https://user-images.githubusercontent.com/7189824/39546169-764f91ae-4e21-11e8-8150-a8cbf6f8446a.png">

**Comment by boonebgorges** [comment]
Thanks for the report. This should now be fixed. I also added logic so that when you select the 'external' radio button (during create or edit), the Privacy box disappears.

**Comment by bree-z** [comment]
Thanks, Boone!  This looks good for all groups except portfolios.  I still see site privacy settings during creation and when editing settings.

![screen shot 2018-05-02 at 5 44 03 pm](https://user-images.githubusercontent.com/7189824/39550806-95514822-4e30-11e8-93af-83caec80560f.png)

**Comment by boonebgorges** [comment]
I'm not able to reproduce. Could you please be sure you're testing with a cleared cache?

**Comment by bree-z** [comment]
Sorry!  I did a hard refresh, but I just cleared my cache and tried again and this seems to have done the trick.  Thanks!
